#!/bin/bash
#
# pop-up calendar for dzen
#
# (c) 2007, by Robert Manea
#
 
TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
 
(
echo '^bg(#000000)^fg(#111111)'`date +'%A, %d.%m.%Y %H:%M'`
 
# current month, highlight header and today
cal -h | sed -r -e "1,2 s/.*/^fg(white)&^fg()/" \
-e "s/(^| )($TODAY)($| )/\1^bg(white)^fg(#000)\2^fg()^bg()\3/"

# next month, hilight header
[ $MONTH -eq 12 ] && YEAR=`expr $YEAR + 1`
cal `expr \( $MONTH + 1 \) % 12` $YEAR \
    | sed -e "1,2 s/.*/^fg(white)&^fg()/"
) \
    | dzen2 -p 60 -fg "#c8e7a8" -bg "#1a1a1a" -fn '-*-fixed-*-*-*-*-12-*-*-*-*-*-*-*' -x 3000 -y 15 -w 180 -l 20 -sa c -e 'onstart=uncollapse;button3=exit'
