local auto_group = vim.api.nvim_create_augroup(
    "AutoGroup",
    { clear = true }
    )
-- vim.api.nvim_create_autocmd({ 'BufWinLeave', 'WinLeave' }, {
--     group = auto_group,
--     pattern = { "*" },
--     command = 'set nonumber'
-- })
-- TODO: vim.api.nvim_create_autocmd({ 'BufNewFile', 'BufRead' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*" },
-- TODO:     command = 'setlocal formatoptions-=t formatoptions-=c'
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'BufWritePre' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*" },
-- TODO:     command = ':%s/\\s\\+$//e'
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'WinEnter' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*" },
-- TODO:     command = 'setlocal cursorline'
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'WinEnter' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*" },
-- TODO:     command = 'setlocal cursorcolumn'
-- TODO: })
-- TODO: -- vim.api.nvim_create_autocmd({ 'WinLeave' }, {
-- TODO: --     group = auto_group,
-- TODO: --     pattern = { "*" },
-- TODO: --     command = 'setlocal nocursorline'
-- TODO: -- })
-- TODO: vim.api.nvim_create_autocmd({ 'WinLeave' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*" },
-- TODO:     command = 'setlocal nocursorcolumn'
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'BufWinEnter', 'WinEnter' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*" },
-- TODO:     command = ''
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'BufEnter' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "*i3/config" },
-- TODO:     command = 'setlocal filetype=i3'
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'FileType' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "markdown", "md" },
-- TODO:     command = 'setlocal spell'
-- TODO: })
-- TODO: vim.api.nvim_create_autocmd({ 'FileType' }, {
-- TODO:     group = auto_group,
-- TODO:     pattern = { "powershell", "ps1" },
-- TODO:     command = 'set colorcolumn=115'
-- TODO: })


